### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by j-tee** [AdnanOlarmmi/To-Do-List-App#7]
Good Job!!!
 I will however suggest on this line 
https://github.com/AdnanOlarmmi/To-Do-List-App/blob/beeadaa6611e2ff1bf0ffe96c12f905cf06854f0/edit_clear_completed.test.js#L17
use `toBeTruthy()` instead of `toBe(true)`

**Comment by AdnanOlarmmi** [comment]
Thank you @j-tee
